name: "[FEATURE] Build e PR"

on:
  push:
    branches:
      - feature**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Instalar Maven
        run: sudo apt-get install maven

      - name: Construir projeto com Maven
        run: mvn clean install -DskipTests

      - name: Instalar GitHub CLI
        run: sudo apt-get install gh

      - name: Autenticar com GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Obter nome da branch atual
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Enviar branch de feature para o remoto
        run: git push origin $BRANCH_NAME

      - name: Criar pull request
        run: |
          gh pr create --base main --head $BRANCH_NAME --title "Merge main <-- $BRANCH_NAME" --body "Pull request automático"

permissions:
  contents: write
  pull-requests: write